services:

  backend:
    build: .docker
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:8000"
    volumes:
      - .:/var/www/html
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-"client_host=172.17.0.1 client_port=9003 start_with_request=yes"}
